dhdatadownloader/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', 'dhdatadownloader.main.views.index'),
	url(r'^download/$', 'dhdatadownloader.main.views.download'),
	url(r'^download/downloadFile/$', 'dhdatadownloader.main.views.downloadFile'),
    url(r'^login/$', 'dhdatadownloader.main.views.login'),
    url(r'^logout/$', 'dhdatadownloader.main.views.logout'),
    url(r'^channel$', 'dhdatadownloader.main.views.channel'),
    url(r'^login/facebookLogin/$', 'dhdatadownloader.main.views.facebookLogin'),
    # Examples:
    # url(r'^$', 'dhdatadownloader.views.home', name='home'),
    # url(r'^dhdatadownloader/', include('dhdatadownloader.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

dhdatadownloader/main/models.py
from django.db import models
from django.contrib.auth.models import User

# --------------------------------------- fields.py  --------------------------------------- #

from copy import deepcopy
from base64 import b64encode, b64decode
from zlib import compress, decompress
# try:
#     from cPickle import loads, dumps
# except ImportError:
#     from pickle import loads, dumps

from django.db import models
from django.utils.encoding import force_unicode
from picklefield.fields import PickledObjectField


class DHPhoto(models.Model):
	description = models.CharField(max_length=200, blank=True, null=True)
	level = models.IntegerField(blank=True, null=True)
	userID = models.CharField(max_length=200, blank=True, null=True)
	location = models.CharField(max_length=200, blank=True, null=True)
	latitude = models.FloatField(blank=True, null=True)
	longitude = models.FloatField(blank=True, null=True)
	timestamp = models.DateTimeField(blank=True, null=True)
	photoURL = models.CharField(max_length=200, blank=True, null=True)
	objectID = models.CharField(max_length=200)
	createdAt = models.DateTimeField(blank=True, null=True)
	params = PickledObjectField()

	def __unicode__(self):
		return 'Description: ' + self.description + '\n' + 'ObjectID: ' + self.objectID

class DHUserProfile(models.Model):
	user = models.OneToOneField(User)
	parseToken = models.CharField(max_length=200)

dhdatadownloader/main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Context, loader, RequestContext
from django.contrib import sessions
from django.conf import settings
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django import forms, shortcuts
import csv
import datetime
from Frameworks import ParsePy
import xlwt
from bootstrap.forms import BootstrapForm, Fieldset
from models import DHPhoto, DHUserProfile
from django.db.models import Max
from django.core.servers.basehttp import FileWrapper
from django.core.files import File
import os.path

now = datetime.datetime.now()

class QueryForm(forms.Form):
    limit = forms.IntegerField()
    startdate = forms.DateField(now, '%m/%d/%y')
    enddate = forms.DateField(now, '%m/%d/%y')

class LoginForm(BootstrapForm):
    class Meta:
        layout = (
            Fieldset("Please Login", "username", "username", "password"),
        )
    password = forms.CharField(widget=forms.PasswordInput(), max_length=100)
    username = forms.CharField(max_length=100)
    

ParsePy.APPLICATION_ID = "53Rdo20D9PA1hiPTN7qPzcPVaNQEmAkMXi3j6tLv"
ParsePy.MASTER_KEY = "FqhBINgpfI1ISF1ao2poRHYzvhbbr6PjJvuij0cq"

def channel(request):
    return HttpResponse('<script src="//connect.facebook.net/en_US/all.js"></script>')

def index(request):
    loggedIn = False
    if 'session_id' in request.session:
        loggedIn = True
    x = 'hi'
    t = loader.get_template('templates/index.html')
    c = Context({
        'x' : x,
        'loggedIn' : loggedIn
    })
    return HttpResponse(t.render(c))

def download(request):
    if request.method == 'POST':
        form = QueryForm(request.POST)
        if form.is_valid():
            return downloadFile(request)
    else: 
        bform = LoginForm()
        print bform
        t = loader.get_template('templates/download.html')
        c = RequestContext(request, {
            'form' : bform,
        })
        return HttpResponse(t.render(c))

def login(request):
    login_failed = False
    if 'session_id' in request.session:
        print "Logged In"
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username =request.POST['username']
        password = request.POST['password']

        parseUser = ParsePy.ParseUser()
        parseUser.login(username, password)

        if parseUser.session_token:
            print parseUser.session_token
            # try:
            #     user = User.objects.get(username=username)
            #     print 'USER FOUND'
            # except User.DoesNotExist:
            #     print 'BEFORE USER'
            #     # user = User.objects.create_user(username=username, email=parseUser.email, password=password)
            #     user = User.objects.create_user('timshi', 'timgshi@gmail.com', 'a071170')
            #     # print 'USER: ' + user
            #     print 'BEFORE SAVE'
            #     user.save()
            #     print 'after save'
            #     # dhUserProfile = DHUserProfile()
            #     # dhUserProfile.user = user
            #     # dhUserProfile.parseToken = parseUser.session_token
            #     # dhUserProfile.save()

            # print 'BEFORE AUTHENTICATE'
            # user = authenticate(username=username, password=password)
            # print 'AFTER AUTHENTICATE'
            # print user
            # auth_login(request, user)
            # print 'AFTER LOGIN'
            request.session['session_id'] = parseUser.session_token
            request.session['user_id'] = parseUser._object_id
            return HttpResponseRedirect('/')
        else:
            login_failed = True
            print "LOGIN FAILED"

    t = loader.get_template('templates/login.html')
    bform = LoginForm()
    c = RequestContext(request, {
        'form' : bform,
        'login_failed' : login_failed
    })
    return HttpResponse(t.render(c))

def facebookLogin(request):
    print 'fblogin'
    try:
        print 'before'
        userID = request.POST['userID']
        print 'user'
        accessToken = request.POST['accessToken']
        print 'access'
        expiresIn = request.POST['expiresIn']
        print 'expire'
        print userID
        print accessToken
        print expiresIn
        print 'before login'
        parseUser = ParsePy.ParseUser()
        parseUser.facebookLogin(userID, accessToken, expiresIn)
        print 'after login'
        if parseUser.session_token:
            print parseUser.session_token
            request.session['session_id'] = parseUser.session_token
            request.session['user_id'] = parseUser._object_id
            return HttpResponseRedirect('/')

    except KeyError:
        print 'fb key error'
    

def logout(request):
    try:
        del request.session['session_id']
    except KeyError:
        pass
    return HttpResponseRedirect('/')

def downloadFile(request):

    response = HttpResponse(mimetype='text/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename=dhdata-%s.xls' % now.strftime('%d-%m-%y')

    if 'session_id' in request.session:
        f = open(os.path.join(os.path.dirname(__file__), 'dhdata-latest.xlsx'), 'r')
        # myfile = File(f)
        response = HttpResponse((f), content_type='text/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename=dhdata-%s.xlsx' % now.strftime('%d-%m-%y')
        f.close
        # updateDB()
        # wb = xlwt.Workbook()
        # ws = wb.add_sheet('DH Data')

        # f = xlwt.Font()
        # f.height = 20*10
        # f.name = 'Arial'
        # f.bold = False
        # f.underline = xlwt.Font().UNDERLINE_SINGLE
        # f.colour_index = 4

        # h_style = xlwt.XFStyle()
        # h_style.font = f
        # # limit = int(request.GET.get('limit'))
        # # if limit > 1000 or limit < 0:
        # #     limit = 20
        # # print limit
        # # query = ParsePy.ParseQuery("DHPhoto").limit(limit)
        # # query.order("updatedAt", True)
        # # objects = query.fetch();
        # # headers = ['description', 'level', 'userID', 'location', 'latitude', 'longitude', 'date', 'photoURL']
        # # for x in range((len(headers))):
        # #     ws.write(0,x,headers[x])
        # # row = 1
        # # for x in objects:
        # #     try:
        # #         data = [x.DHDataSixWord, x.DHDataHappinessLevel, x.PFUser._object_id, x.DHDataLocationString, x.geopoint._latitude, x.geopoint._longitude, x._created_at, x.photoData.url]
        # #         for col in range((len(data))):
        # #             if col == len(data) - 1:
        # #                 ws.write(row, col, xlwt.Formula("HYPERLINK" + '("%s";"photo")' % data[col]), h_style)
        # #             else:
        # #                 ws.write(row, col, data[col])
        # #         row += 1
        # #     except AttributeError:
        # #         print("att error")

        # # wb.save(response)
        # objects = []
        # personal = request.GET.get('personal')
        # if personal == 'true':
        #     objects = DHPhoto.objects.filter(userID__iexact=request.session['user_id']).order_by('-createdAt')
        # else:
        #     objects = DHPhoto.objects.order_by('-createdAt')
        # # headers = ['description', 'level', 'userID', 'location', 'latitude', 'longitude', 'date', 'photoURL', 'objectID']
        # # for x in range((len(headers))):
        # #     ws.write(0,x,headers[x])
        # # row = 1
        # # for photo in objects:
        # #     data = [photo.description, photo.level, photo.userID, photo.location, photo.latitude, photo.longitude, photo.timestamp.strftime("%Y-%m-%d %H:%M:%S"), photo.photoURL, photo.objectID]
        # #     for col in range((len(data))):
        # #         if col == len(data) - 2:
        # #             ws.write(row, col, xlwt.Formula("HYPERLINK" + '("%s";"photo")' % data[col]), h_style)
        # #         else:
        # #             ws.write(row, col, data[col])
        # #     row += 1
        # # csvArray = []
        # # headers = []
        # # row = 1
        # # for photo in objects:
        # #     photoArray = []
        # #     for x in photo.params:
                
        # #         if x not in 'DHDataWhoTook' and x not in 'ACL':
        # #             col = 0
        # #             try:
        # #                 col = headers.index(x)
        # #             except ValueError:
        # #                 headers.append(x)
        # #                 col = headers.index(x)
        # #             cellValue = "%s" % photo.params.get(x)
        # #             cellValue = cellValue.encode('ascii', 'ignore')
        # #             photoArray.insert(col, cellValue)
        # #             print photoArray
        # #             # ws.write(row, col, "%s" % photo.params.get(x))
        # #     csvArray.insert(row, photoArray)
        # #     row += 1
        # # for header in headers:
        #     # ws.write(0, headers.index(header), header)
        # csvArray = []
        # headers = ['DHDataGeoLat', 'DHDataGeoLong', 'DHDataHappinessLevel', 'DHDataLocationString', 'DHDataSixWord', 'DHDataTimestamp', 'DHDataWeatherCondition', 'DHDataWeatherTemperature', 'photoData', '_created_at', '_updated_at', '_object_id']
        # csvArray.append(headers)
        # for photo in objects:
        #     photoArray = []
        #     for x in headers:
        #         cellValue = "%s" % photo.params.get(x)
        #         cellValue = cellValue.encode('ascii', 'ignore')
        #         photoArray.append(cellValue)
        #     csvArray.append(photoArray)
        # response = HttpResponse(mimetype='text/csv')
        # response['Content-Disposition'] = 'attachment; filename=dhdata-%s.csv' % now.strftime('%d-%m-%y')
        # # csvArray.insert(0, headers)

        # writer = csv.writer(response)

dhdatadownloader/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Tim Shi">

  <!-- Facebook Open Graph Tags -->
  <meta property="og:title" content="DH Data Downloader" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="http://dhdatadownloader.herokuapp.com" />
  <meta property="og:image" content="http://i.imgur.com/rG1Or.png" />
  <meta property="og:site_name" content="DH Data Downloader" />
  <meta property="fb:admins" content="1063320196" />
  <!-- <link rel="stylesheet" href="style.css" /> -->
  <title>{% block title %}Designing Happiness Data Download{% endblock %}</title>
  {% load bootstrap %}
  {% bootstrap_css %}
  <style type="text/css">
  body {
    padding-top: 60px;
    padding-bottom: 40px;
  }
  </style>
  <link href="/static/bootstrap-responsive.css" rel="stylesheet">
  <link rel="shortcut icon" href="http://www.iconj.com/ico/w/d/wdlw5mqh0h.ico" type="image/x-icon" />
  <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
  <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">
  {% block head %}{% endblock %}
</head>

<body>


  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">DH Data Downloader</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="http://www.stanford.edu/class/mktg355/">MKTG 355</a></li>
            {%block navbar %}{% endblock %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>




  {%block content %}{% endblock %}

  <!-- Facebook -->
  <div id="fb-root"></div>
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '171752956231417',
      channelUrl : '//'+window.location.hostname+'/channel',
      status     : true, 
      cookie     : true,
      xfbml      : true,
      oauth      : true,
    });
    {% block fbinit %}{% endblock %}
  };

  (function(d){
   var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
   js = d.createElement('script'); js.id = id; js.async = true;
   js.src = "//connect.facebook.net/en_US/all.js";
   d.getElementsByTagName('head')[0].appendChild(js);
 }(document));
  </script>

  <!-- Google Analytics -->
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29443463-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>



<!-- Le javascript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <!-- <script src="../assets/js/jquery.js"></script>
  // <script src="../assets/js/bootstrap-transition.js"></script>
  // <script src="../assets/js/bootstrap-alert.js"></script>
  // <script src="../assets/js/bootstrap-modal.js"></script>
  // <script src="../assets/js/bootstrap-dropdown.js"></script>
  // <script src="../assets/js/bootstrap-scrollspy.js"></script>
  // <script src="../assets/js/bootstrap-tab.js"></script>
  // <script src="../assets/js/bootstrap-tooltip.js"></script>
  // <script src="../assets/js/bootstrap-popover.js"></script>
  // <script src="../assets/js/bootstrap-button.js"></script>
  // <script src="../assets/js/bootstrap-collapse.js"></script>
  // <script src="../assets/js/bootstrap-carousel.js"></script>
  // <script src="../assets/js/bootstrap-typeahead.js"></script> -->

  <script src="/static/bootstrap.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
</body>
</html>

dhdatadownloader/main/templates/download.html
{% extends "templates/base.html" %}


{% block content %}



<!-- <form action="download" method="post">
{% csrf_token %}

{{form.as_p}}
<label for="id_startdate">Start Date (mm/dd/yy)</label>
<input type="submit" value="Vote" />
</form>  -->





<p><a href="downloadFile">Click here to download</a></p>
{% endblock %}

dhdatadownloader/main/templates/index.html
{% extends "templates/base.html" %}

{%block head %}
<script type="text/javascript">
(function() {
	var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
	po.src = 'https://apis.google.com/js/plusone.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>
<!-- Update your html tag to include the itemscope and itemtype attributes -->
<html itemscope itemtype="http://schema.org/Product">

<!-- Add the following three tags inside head -->
<meta itemprop="name" content="DH Data Downloader">
<meta itemprop="description" content="Download the DH App Data">
<meta itemprop="image" content="http://i.imgur.com/rG1Or.png">
{% endblock %}

{% block navbar %}
{% if loggedIn %}
<li><a href="/logout">Logout</a></li>
{% else %}
<li><a href="/login">Login</a></li>
{% endif %}
{% endblock %}

{% block content %}



<div class="container">

	<!-- Main hero unit for a primary marketing message or call to action -->
	<div class="hero-unit">
		<h1>Welcome to the DH Data Downloader!</h1>
		{% if loggedIn %}
		<p>Please select download options from the choices below.</p>
		<p>
			<a class="btn btn-primary btn-large" href="/download/downloadFile?limit=1000&amp;personal=false">Download Full &raquo;</a>
			<a class="btn btn-primary btn-large" href="/download/downloadFile?limit=1000&amp;personal=true">Download Personal &raquo;</a>
		</p>
		{% else %}
		<p>From here you'll be able to download an excel spreadsheet of the data collected from the DH app. Please log in to continue.<br />Note: Downloading the full data will take quite some time ( > 5 minutes).</p>
		<p><a class="btn btn-primary btn-large" href="/login">Log in &raquo;</a></p>
		{% endif %}
	</div>
	<div class="row">
		<div class="g-plusone" data-size="medium" data-annotation="inline" data-href="http://dhdatadownloader.herokuapp.com"></div>
	</div>
	<div class="row">
		<div class="fb-like" data-href="http://dhdatadownloader.herokuapp.com" data-send="true" data-width="450" data-show-faces="true"></div>
	</div>

</div>


{% endblock %}

dhdatadownloader/main/templates/login.html
{% extends "templates/base.html" %}

{% block fbinit %}
FB.Event.subscribe('auth.statusChange', function(response) {
	//alert('logged in');
	if (response.authResponse) {
		
	}
	FB.getLoginStatus(function(response) {
		var accessToken = FB.getAuthResponse()['accessToken'];
		var expiresIn = FB.getAuthResponse()['expiresIn'];
		var userID = FB.getAuthResponse()['userID'];
		var postdata={
          'csrfmiddlewaretoken': '{{ csrf_token }}',
          'accessToken' : accessToken,
          'userID' : userID,
          'expiresIn': expiresIn
          //'accessToken': FB.getAuthResponse()['accessToken'].val(),
          //'expiresIn': FB.getAuthResponse()['expiresIn'].val(),
          //'userID': FB.getAuthReponse()['userID'].val()
     	}
		//$.post('facebookLogin/', postdata, function(data) {
			
			//window.location.replace('/');
			
  			//alert('hi');
  			//$('.result').html(data);
		//});
	});
	
		//alert('logged in');
		//alert(FB.getAuthResponse()['accessToken']+FB.getAuthResponse()['expiresIn']+FB.getAuthResponse()['userID']);
		//alert(FB.getAuthResponse()['expiresIn']);
		//alert(FB.getAuthResponse()['userID']);

		
	
});
{% endblock %}

{% block content %}




<div class="row-fluid">
	<div class="span12">
		<div class="row-fluid">
			<div class="span4"></div>
			<div class="span4">
				{% if login_failed %}
				<div class="alert alert-error">
					<p>Oops, looks like your username or password is incorrect.<br /> Please try again.</p>

				</div>
				{% endif %}
				<form action="/login/" method="post" class="form-horizontal">
					{% csrf_token %}
					{{ form }}
					<div class="form-actions">
						<button type="submit" class="btn btn-primary">Login</button>
					</div>
				</form>
				<div class="fb-login-button" data-show-faces="true" data-width="200" data-max-rows="1"></div>
			</div>
		</div>
	</div>
</div>
</div>




{% endblock %}